import math
import time
import traceback

from aiogram import Router, F, Bot
from aiogram.exceptions import AiogramError
from aiogram.types import Message, ErrorEvent, BufferedInputFile, CallbackQuery
from aiogram.utils.keyboard import InlineKeyboardBuilder

message_limit = 3970


def get_support_markup(url: str):
    builder = InlineKeyboardBuilder()

    builder.button(text='üÜò –ü–æ–¥–¥–µ—Ä–∂–∫–∞', url=url)
    builder.adjust(1)

    return builder.as_markup()


def get_user_markup(user_url: str):
    builder = InlineKeyboardBuilder()

    builder.button(text='üë§ –ü–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å', url=user_url)
    builder.adjust(1)

    return builder.as_markup()


async def report(bot: Bot, owners: list[int], object_name: str, text: str, username: str,
                 user_id: int,
                 user_url: str):
    traceback_log = BufferedInputFile(traceback.format_exc().encode(),
                                      filename=f"Traceback{math.floor(time.time())}.txt")
    for admin in owners:
        try:
            await bot.send_document(admin, traceback_log,
                                    caption=f'‚ö†Ô∏è –ü—Ä–æ–∏–∑–æ—à–ª–∞ –æ—à–∏–±–∫–∞ –ø—Ä–∏ –æ–±—Ä–∞–±–æ—Ç–∫–µ {object_name} –æ—Ç @{username} [<code>{user_id}</code>]!\n'
                                            f'<pre>{text}</pre>',
                                    reply_markup=get_user_markup(user_url))
        except AiogramError:
            pass


def add_to_router(main_router: Router, main_bot: Bot, owners: list[int], url: str):
    error_handler_router = Router()

    @error_handler_router.error(F.update.message.as_("message"))
    async def error_handler(_exception: ErrorEvent, message: Message):
        await message.reply('‚ùå –ü–æ—Ö–æ–∂–µ, —á—Ç–æ-—Ç–æ –ø–æ—à–ª–æ –Ω–µ —Ç–∞–∫, —Ä–µ–ø–æ—Ä—Ç –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω', reply_markup=get_support_markup(url))

        await report(main_bot, owners, '—Å–æ–æ–±—â–µ–Ω–∏—è', message.text, message.from_user.username,
                     message.from_user.id,
                     message.from_user.url)

    @error_handler_router.error(F.update.callback_query.as_("query"))
    async def error_handler(_exception: ErrorEvent, query: CallbackQuery):
        await query.answer('‚ùå –ü–æ—Ö–æ–∂–µ, —á—Ç–æ-—Ç–æ –ø–æ—à–ª–æ –Ω–µ —Ç–∞–∫, —Ä–µ–ø–æ—Ä—Ç –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω', show_alert=True)

        await report(main_bot, owners, '–∫–Ω–æ–ø–∫–∏', query.data, query.from_user.username, query.from_user.id,
                     query.from_user.url)

    main_router.include_router(error_handler_router)
